---
title: "Day 9 Comp"
author: "Peter Menzies"
date: "8/19/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)
library(palmerpenguins)
library(lubridate)
library(janitor)
```

### janitor::get_dupes()

```{r}
star_dupes_height <- starwars %>% 
  get_dupes(height, eye_color)
```

### dplyr::across()

```{r}
sw_across <- starwars %>% 
  mutate(across(where(is.character), tolower))
```

#### Find the mean of multiple columns with across() 
```{r}
starwars %>% 
  group_by(homeworld) %>% 
  summarize(across(where(is.numeric), mean, na.rm = TRUE))

# NaN returned when there are no observations for a variable (0/0 = NaN)
```

### Basic / common troubleshooting stuff

```{r}
starwars %>% 
  filter(homeworld = "Naboo")
```

```{r}
starwars %>% 
  separate(skin_color, into = c("skin_1,", "skin_2", "col_3"), sep = ",")
```

```{r}
# misplaces pipe operator:

ggplot(mtcars, aes(x = wt, y = mpg)) %>% 
  geom_point()
```

```{r}
troubleshooting <- penguins %>% 
      mutate(across(where(is.numeric), as.character)) %>% 
      mutate(island = fct_relevel(island, c("Dream", "Biscoe", "Torgersen"))) %>% 
      unite(island_yr, c(island, year), sep = "_") %>% 
      filter(species %in% c("Adelie", "Chinstrap")) %>% 
      relocate(island_yr, .after = species) %>% 
      rename(penguins_spp = species)
```


```{r}
library(tidyverse)

df <- tribble(
  ~name, ~height, ~hair_color,
  "Teddy", 2.2, "brown",
  "Khora", 3.1, "white",
  "Waffle", 1.0, "tan"
)

df %>% 
  filter(name == "Waffle")
```


